from setuptools import setup, find_packages

setup(
    name="pgcbacktest",
    version="0.1.0",
    description="A Python package for backtesting trading strategies",
    long_description="pgcbacktest is a Python module designed for backtesting trading strategies using pandas, numpy, and other essential libraries.",
    long_description_content_type="text/plain",
    author="Vikas Sharma",
    author_email="Jnv2252@Gmail.com",
    license="MIT",
    packages=find_packages(),
    install_requires=[
        "pandas==2.3.3",
        "polars==1.39.0",
        "plotly==6.5.2",
        "numpy==2.2.6",
        "dask==2026.1.2",
        "numba==0.64.0",
        "streamlit==1.55.0",
        "rarfile",
        "filelock",
        "matplotlib",
        "requests",
        "tqdm",
    ],
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
)
